// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package persistence

import (
	"context"
	"database/sql"

	"gorm.io/gorm"

	"gorm.io/gen"

	"gorm.io/plugin/dbresolver"
)

var (
	Q         = new(Query)
	WorkFlow  *workFlow
	WorkNode  *workNode
	WorkOrder *workOrder
)

func SetDefault(db *gorm.DB, opts ...gen.DOOption) {
	*Q = *Use(db, opts...)
	WorkFlow = &Q.WorkFlow
	WorkNode = &Q.WorkNode
	WorkOrder = &Q.WorkOrder
}

func Use(db *gorm.DB, opts ...gen.DOOption) *Query {
	return &Query{
		db:        db,
		WorkFlow:  newWorkFlow(db, opts...),
		WorkNode:  newWorkNode(db, opts...),
		WorkOrder: newWorkOrder(db, opts...),
	}
}

type Query struct {
	db *gorm.DB

	WorkFlow  workFlow
	WorkNode  workNode
	WorkOrder workOrder
}

func (q *Query) Available() bool { return q.db != nil }

func (q *Query) clone(db *gorm.DB) *Query {
	return &Query{
		db:        db,
		WorkFlow:  q.WorkFlow.clone(db),
		WorkNode:  q.WorkNode.clone(db),
		WorkOrder: q.WorkOrder.clone(db),
	}
}

func (q *Query) ReadDB() *Query {
	return q.ReplaceDB(q.db.Clauses(dbresolver.Read))
}

func (q *Query) WriteDB() *Query {
	return q.ReplaceDB(q.db.Clauses(dbresolver.Write))
}

func (q *Query) ReplaceDB(db *gorm.DB) *Query {
	return &Query{
		db:        db,
		WorkFlow:  q.WorkFlow.replaceDB(db),
		WorkNode:  q.WorkNode.replaceDB(db),
		WorkOrder: q.WorkOrder.replaceDB(db),
	}
}

type queryCtx struct {
	WorkFlow  IWorkFlowDo
	WorkNode  IWorkNodeDo
	WorkOrder IWorkOrderDo
}

func (q *Query) WithContext(ctx context.Context) *queryCtx {
	return &queryCtx{
		WorkFlow:  q.WorkFlow.WithContext(ctx),
		WorkNode:  q.WorkNode.WithContext(ctx),
		WorkOrder: q.WorkOrder.WithContext(ctx),
	}
}

func (q *Query) Transaction(fc func(tx *Query) error, opts ...*sql.TxOptions) error {
	return q.db.Transaction(func(tx *gorm.DB) error { return fc(q.clone(tx)) }, opts...)
}

func (q *Query) Begin(opts ...*sql.TxOptions) *QueryTx {
	tx := q.db.Begin(opts...)
	return &QueryTx{Query: q.clone(tx), Error: tx.Error}
}

type QueryTx struct {
	*Query
	Error error
}

func (q *QueryTx) Commit() error {
	return q.db.Commit().Error
}

func (q *QueryTx) Rollback() error {
	return q.db.Rollback().Error
}

func (q *QueryTx) SavePoint(name string) error {
	return q.db.SavePoint(name).Error
}

func (q *QueryTx) RollbackTo(name string) error {
	return q.db.RollbackTo(name).Error
}
